- name: Deploy the stack (cluster)
  cloudformation:
    stack_name: "{{ rds_stack_name }}"
    template_parameters:
      MultiAZ: "{{ rds_use_multi_az }}"
      DatabaseName: "{{ rds_db_name }}"
      Engine: "{{ rds_engine }}"
      MasterUserPassword: "{{ rds_password }}"
      MasterUsername: "{{ rds_username }}"
      SecurityGroups: "{{ rds_temp_sgs | default(rds_security_groups)  }}"
      SubnetGroup: "{{ rds_subnet_group_name }}"
      Port: "{{ rds_port }}"
      EngineVersion: "{{ rds_engine_version }}"
      KMSKeyId: "{{ rds_kms_key_id }}"
      UseEncryption: "{{ rds_use_encrypted_storage }}"
      ClusterParameterGroupName: "{{ rds_cluster_parameter_group_name }}"
      DBParameterGroupName: "{{ rds_parameter_group_name }}"
      ClusterAZs: "{{ rds_cluster_zones }}"
      AllowMajorVersionUpgrade: "{{ rds_allow_major_version_upgrade }}"
      AutoMinorVersionUpgrade: "{{ rds_auto_minor_version_upgrade }}"
      Timezone: "{{ rds_timezone }}"
      PubliclyAccessible: "{{ rds_publicly_accessible }}"
      LicenseModel: "{{ rds_license_model }}"
      MonitoringRoleArn: "{{ rds_monitoring_role_arn }}"
      MonitoringInterval: "{{ rds_monitoring_internal }}"
      OptionGroupName: "{{ rds_option_group_name }}"
      Domain: "{{ rds_domain }}"
      DomainIAMRoleName: "{{ rds_iam_role_arn }}"
      Iops: "{{ rds_iops }}"
      DBInstanceClass: "{{ rds_instance_class }}"
      TdeCredentialArn: "{{ rds_tde_credential_arn }}"
      TdeCredentialPassword: "{{ rds_credential_password }}"
      BackupRetentionPeriod: "{{ rds_backup_retention_period }}"
      CopyTagsToSnapshot: "{{ rds_copy_tags_to_snapshot }}"
    region: "{{ rds_region }}"
    disable_rollback: "{{ rds_disable_rollback }}"
    template: "{{ rds_template }}"
    state: "{{ rds_stack_state }}"
    tags: "{{ rds_tags }}"
  register: rds_cluster
